name: Build and Deploy to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install numpy scipy matplotlib requests

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - name: Build project
        run: |
          mkdir build
          cd build
          ../configure
          ninja

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
