name: Build and Deploy to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        run: |
          sh <(curl -L https://nixos.org/nix/install) --no-daemon
          mkdir -p ~/.config/nix
          echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf

      - name: Build project
        run: |
          . ~/.nix-profile/etc/profile.d/nix.sh
          nix develop --command bash -c 'mkdir build && cd build && ../configure && ninja'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
